"""
EditFlow AI - MCP Client

The MCP Client manages communication between the AI Director and all MCP servers.
It handles task scheduling, execution, and progress tracking.
"""

import asyncio
import uuid
from typing import Any, Optional

from loguru import logger

from .protocol import (
    EditPlan,
    MCPRequest,
    MCPResponse,
    MCPServer,
    MCPServerType,
    TaskNode,
)


class MCPClient:
    """
    Central client for managing all MCP servers.
    
    The MCP Client is responsible for:
    - Registering MCP servers
    - Routing requests to appropriate servers
    - Managing task execution order based on dependencies
    - Tracking progress and handling cancellations
    """

    def __init__(self):
        self.servers: dict[MCPServerType, MCPServer] = {}
        self.pending_requests: dict[str, MCPRequest] = {}
        self.running_tasks: dict[str, asyncio.Task] = {}
        self.task_results: dict[str, MCPResponse] = {}

    def register_server(self, server: MCPServer) -> None:
        """Register an MCP server."""
        server_type = server.server_type
        if server_type in self.servers:
            logger.warning(f"Server {server_type} already registered, replacing")
        self.servers[server_type] = server
        logger.info(f"Registered MCP server: {server_type.value}")

    def get_server(self, server_type: MCPServerType) -> Optional[MCPServer]:
        """Get a registered server by type."""
        return self.servers.get(server_type)

    def list_available_tools(self) -> list[dict[str, Any]]:
        """List all available tools from all registered servers."""
        tools = []
        for server in self.servers.values():
            for tool in server.tools:
                tools.append({
                    "name": tool.name,
                    "description": tool.description,
                    "parameters": tool.parameters,
                    "server_type": tool.server_type.value,
                })
        return tools

    async def execute_plan(self, plan: EditPlan) -> dict[str, MCPResponse]:
        """
        Execute an edit plan generated by the AI Director.
        
        This method:
        1. Validates all tasks can be executed
        2. Creates a dependency graph
        3. Executes tasks in parallel where possible
        4. Returns results for all tasks
        """
        logger.info(f"Executing edit plan: {plan.plan_id}")
        
        results: dict[str, MCPResponse] = {}
        task_status: dict[str, str] = {task.id: task.status for task in plan.tasks}
        
        # Build dependency map
        task_map = {task.id: task for task in plan.tasks}
        
        async def execute_task(task: TaskNode) -> MCPResponse:
            """Execute a single task."""
            task.status = "running"
            logger.info(f"Executing task {task.id}: {task.tool_name}")
            
            try:
                server = self.servers.get(task.server_type)
                if not server:
                    return MCPResponse(
                        request_id=task.id,
                        success=False,
                        error=f"Server {task.server_type.value} not found",
                    )
                
                response = await server.execute_tool(task.tool_name, task.parameters)
                task.result = response
                task.status = "completed" if response.success else "failed"
                return response
                
            except Exception as e:
                logger.error(f"Task {task.id} failed: {e}")
                response = MCPResponse(
                    request_id=task.id,
                    success=False,
                    error=str(e),
                )
                task.result = response
                task.status = "failed"
                return response
        
        # Execute tasks respecting dependencies
        completed_tasks: set[str] = set()
        
        while len(completed_tasks) < len(plan.tasks):
            # Find tasks that are ready to run (all dependencies completed)
            ready_tasks = []
            for task in plan.tasks:
                if task.id in completed_tasks:
                    continue
                if task.status == "running":
                    continue
                    
                # Check if all dependencies are completed
                deps_satisfied = all(
                    dep in completed_tasks for dep in task.dependencies
                )
                if deps_satisfied:
                    ready_tasks.append(task)
            
            if not ready_tasks:
                # Check for circular dependencies or failures
                remaining = [t for t in plan.tasks if t.id not in completed_tasks]
                if any(t.status == "failed" for t in remaining):
                    logger.error("Task failed, stopping execution")
                    break
                logger.error("No ready tasks - possible circular dependency")
                break
            
            # Execute ready tasks in parallel
            tasks_to_run = [execute_task(task) for task in ready_tasks]
            task_responses = await asyncio.gather(*tasks_to_run, return_exceptions=True)
            
            for task, response in zip(ready_tasks, task_responses):
                if isinstance(response, Exception):
                    results[task.id] = MCPResponse(
                        request_id=task.id,
                        success=False,
                        error=str(response),
                    )
                else:
                    results[task.id] = response
                    if response.success:
                        completed_tasks.add(task.id)
        
        logger.info(f"Edit plan {plan.plan_id} completed")
        return results

    async def execute_single_tool(
        self,
        server_type: MCPServerType,
        tool_name: str,
        parameters: dict[str, Any],
    ) -> MCPResponse:
        """Execute a single tool directly."""
        server = self.servers.get(server_type)
        if not server:
            return MCPResponse(
                request_id=str(uuid.uuid4()),
                success=False,
                error=f"Server {server_type.value} not found",
            )
        
        return await server.execute_tool(tool_name, parameters)

    async def cancel_task(self, request_id: str) -> bool:
        """Cancel a running task."""
        if request_id in self.running_tasks:
            task = self.running_tasks[request_id]
            task.cancel()
            logger.info(f"Cancelled task: {request_id}")
            return True
        
        # Try to cancel on server
        for server in self.servers.values():
            if await server.cancel_task(request_id):
                return True
        
        return False

    def get_progress(self, plan_id: str) -> dict[str, float]:
        """Get progress for all tasks in a plan."""
        progress = {}
        for task_id, response in self.task_results.items():
            if task_id.startswith(plan_id):
                progress[task_id] = response.progress
        return progress
