"""
EditFlow AI - MCP Server Protocol Definitions

This module defines the Model Context Protocol (MCP) interface for communication
between the AI Director (Gemma) and various MCP servers.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional


class MCPServerType(Enum):
    """Enumeration of all MCP server types."""
    VIDEO = "video"
    TIMELINE = "timeline"
    AUDIO = "audio"
    SPEECH = "speech"
    VISION = "vision"
    SUBTITLE = "subtitle"
    EFFECTS = "effects"
    COLOR = "color"
    EXPORT = "export"
    RENDER = "render"


@dataclass
class MCPTool:
    """Represents an MCP tool/function that can be called."""
    name: str
    description: str
    parameters: dict[str, Any]
    server_type: MCPServerType


@dataclass
class MCPRequest:
    """Request sent to an MCP server."""
    tool_name: str
    parameters: dict[str, Any]
    request_id: str
    priority: int = 0  # Higher = more urgent


@dataclass
class MCPResponse:
    """Response from an MCP server."""
    request_id: str
    success: bool
    result: Any = None
    error: Optional[str] = None
    progress: float = 0.0  # 0.0 to 1.0


@dataclass
class TaskNode:
    """A node in the task execution graph."""
    id: str
    tool_name: str
    server_type: MCPServerType
    parameters: dict[str, Any]
    dependencies: list[str] = field(default_factory=list)
    status: str = "pending"  # pending, running, completed, failed
    result: Optional[MCPResponse] = None


@dataclass
class EditPlan:
    """Complete edit plan generated by the AI Director."""
    plan_id: str
    user_request: str
    tasks: list[TaskNode]
    metadata: dict[str, Any] = field(default_factory=dict)


class MCPServer(ABC):
    """Abstract base class for all MCP servers."""

    @property
    @abstractmethod
    def server_type(self) -> MCPServerType:
        """Return the server type."""
        pass

    @property
    @abstractmethod
    def tools(self) -> list[MCPTool]:
        """Return list of available tools."""
        pass

    @abstractmethod
    async def execute_tool(self, tool_name: str, parameters: dict[str, Any]) -> MCPResponse:
        """Execute a tool with given parameters."""
        pass

    @abstractmethod
    async def cancel_task(self, request_id: str) -> bool:
        """Cancel a running task."""
        pass
